### PR TITLE
Upgraded plugin and dependency versions

### PR DESCRIPTION
**Pull request by behrangsa**
* `maven-compiler-plugin` to `3.7.0`
* `retrolambda-maven-plugin` to `2.5.3`
* `junit` to `4.12`
* `testng` to `6.14.2`

### CODE REVIEW

**Comment by mikolak-net** [comment]
Thanks for the PR! It's high time this got updated. I'll defer it to the weekend, so that I can set up a CI environment.

**Comment by mikolak-net** [comment]
Closing an reopening to trigger Travis build.

**Comment by mikolak-net** [comment]
@behrangsa : tests passed. One question though - any reason not to bump JUnit to 5.x, since we're at it?

**Comment by behrangsa** [comment]
@mikolak-net if JUnit 5 is backwards compatible with JUnit 4, I think we should do it.

Otherwise I suggest releasing two new versions: 

1. `1.0.1` to only include backwards compatible upgrades
2. `2.0.0` to have JUnit 5 and potentially other backwards incompatible upgrades

**Comment by mikolak-net** [comment]
@behrangsa : I'd say a better idea is simply adding an additional value to the `testLibrary` parameter, e.g. `junit5`. 

Should be pretty straightforward - are you up for it, or should I implement that?

**Comment by mikolak-net** [comment]
I'm assuming it's the latter. Merging.

**Comment by behrangsa** [comment]
@mikolak-net sorry, I saw your previous comment awhile ago at work and then forgot to respond to it.

All good mate, thanks for the merge!

**Pull request merged**
